### ISSUE TITLE
HSS: synch failure not handled properly

### ISSUE THREAD

**Issue by dchard** [OPENAIRINTERFACE/openair-cn#39]
[auth_synch_failure.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/2834379/auth_synch_failure.zip)

[HSSrel14_resynch_failure.txt](https://github.com/OPENAIRINTERFACE/openair-cn/files/2842231/HSSrel14_resynch_failure.txt)

I am using the latest "develop" branch of openair-cn and HSSrel14, and I noticed that in case a SQN got unsynchronized, the resynch process on the HSS side is not correct, or to be precise: not implemented.

How to reproduce:

1. Provision a USIM profile in the HSS DB, use it for a while (so the SQN increments).
2. Reset the SQN value in the HSS DB to 0.
3. Try to attach with the SIM again.

Both the old and the new (Rel14) HSS are affected.

The result will be an attach failure with "synch failure" (cause #21), which is correct. In this case the UE sends the AUTS value, from which the HSS should be able to recover the correct USIM(SQN), updated its DB SQN, and send new auth vectors.

However, what the HSSrel14 does is just increments the DB SQN value by 32 each time a synch failure happens. This is not a correct approach, as it can take quite a lot of iterations until the HSS SQN catches up, but after 2 consecutive tries the attach attempt will be rejected. It can also happen that the HSS DB SQN is ahead of the USIM SQN, in this case the +32 iterations can take practically forever, until the 48 bit SQN value turns over.

Attached a PCAP file of the S1AP interface showing this issue, after a USIM got unsynchronized.

**Comment by dchard** [comment]
Updated the issue with the HSS log file.

**Comment by RoadRunnr** [comment]
I've fixed this with a hack:
```
diff --git a/src/hss_rel14/src/s6as6d_impl.cpp b/src/hss_rel14/src/s6as6d_impl.cpp
index 6a97bbc6..615e3d0d 100755
--- a/src/hss_rel14/src/s6as6d_impl.cpp
+++ b/src/hss_rel14/src/s6as6d_impl.cpp
@@ -653,7 +653,7 @@ req->dump();
         }
 
         if (auts_set) {
-            sqn = sqn_ms_derive_cpp (imsisec.opc, imsisec.key, auts, imsisec.rand);
+            sqn = sqn_ms_derive_cpp (imsisec.opc, imsisec.key, auts + 16, imsisec.rand);
             if (sqn != NULL) {
 
               //We succeeded to verify SQN_MS...
```

The root cause is that `sqn_ms_derive` expects auts to contain the AUTS info only, but the S6a DIAMETER Re-Synchronization-Info IE contains the concatenation of RAND and AUTS (3GPP TS 29.272, sect. 7.3.15). The hack blindly skips over the RAND part (it should probably check the length).

**Comment by dchard** [comment]
> I've fixed this with a hack:
> 
> ```
> diff --git a/src/hss_rel14/src/s6as6d_impl.cpp b/src/hss_rel14/src/s6as6d_impl.cpp
> index 6a97bbc6..615e3d0d 100755
> --- a/src/hss_rel14/src/s6as6d_impl.cpp
> +++ b/src/hss_rel14/src/s6as6d_impl.cpp
> @@ -653,7 +653,7 @@ req->dump();
>          }
>  
>          if (auts_set) {
> -            sqn = sqn_ms_derive_cpp (imsisec.opc, imsisec.key, auts, imsisec.rand);
> +            sqn = sqn_ms_derive_cpp (imsisec.opc, imsisec.key, auts + 16, imsisec.rand);
>              if (sqn != NULL) {
>  
>                //We succeeded to verify SQN_MS...
> ```
> 
> The root cause is that `sqn_ms_derive` expects auts to contain the AUTS info only, but the S6a DIAMETER Re-Synchronization-Info IE contains the concatenation of RAND and AUTS (3GPP TS 29.272, sect. 7.3.15). The hack blindly skips over the RAND part (it should probably check the length).

Found the same part in the old HSS, it seems both the rel14 and old HSS are sharing a large portion of the logic.

Will test it, we need to make sure that this works both ways (DB SQN is lower and DB SQN is higher then the MS_SQN).

**Comment by dchard** [comment]
@RoadRunnr To further add to this: I think the problem is likely deeper as it seems even though the MME sends a resynchronization AVP, the HSS just tries to do a normal auth, and a resynch part of the code is not even called.

Does this hack of yours works on your end? Did you tried it?

**Comment by wangchao10101** [comment]
@dchard Excuse me，I meet the same issue。Did you solved this problem? could you share your method? thanks。

**Comment by dchard** [comment]
@wangchao10101 

No, I have not resolved the issue, I just verified that the above solution does not fix the issue.

I find it a bit strange that a major flaw in one of the mandatory base protocols can exist and apparently noone is interested in fixing it, while there is heavy work going on on more "exotic" features.

**Comment by Rodolphe-B** [comment]
I meet the same problem.
I can't yet point where does it come from, but it appears that data HSS is using to calculate the new SQN does not correspond to what the UE sends.

Example

_Wireshark captures this from UE to MME/HSS:_
AUTS value: **b6cd02d0c21879f7a76d336b0e4a**
    SQN_MS xor AK: b6cd02d0c218
    MAC-S: 79f7a76d336b0e4a

_HSS logs this:_
sqn_ms_derive() KEY    : fe.c8.6b.a6.eb.70.7e.d0.89.05.75.7b.1b.b4.4b.8f.
sqn_ms_derive() RAND   : 75.e1.be.72.73.e5.b1.42.4a.24.71.49.c0.26.3c.6b.
sqn_ms_derive() AUTS   : **75.e1.be.72.73.e5.b1.42.4a.24.71.49.c0.26**.
sqn_ms_derive() AK     : 8b.c8.36.f1.f7.3d.
sqn_ms_derive() SQN_MS : fe.29.88.83.84.d8.
sqn_ms_derive() MAC_S  : b1.42.4a.24.71.49.c0.26.

Any workaround ? Maybe setting both the UE and HSS SQN to 0 ? If so, how is it possible to set the OAI ue-softmodem SQN to 0 ?

**Comment by Rodolphe-B** [comment]
I meet the same problem.
I can't yet point where does it come from, but it appears that data HSS is using to calculate the new SQN does not correspond to what the UE sends.

Example

Wireshark captures this from UE to MME/HSS:
AUTS value: b6cd02d0c21879f7a76d336b0e4a
SQN_MS xor AK: b6cd02d0c218
MAC-S: 79f7a76d336b0e4a

HSS logs this:
sqn_ms_derive() KEY : fe.c8.6b.a6.eb.70.7e.d0.89.05.75.7b.1b.b4.4b.8f.
sqn_ms_derive() RAND : 75.e1.be.72.73.e5.b1.42.4a.24.71.49.c0.26.3c.6b.
sqn_ms_derive() AUTS : 75.e1.be.72.73.e5.b1.42.4a.24.71.49.c0.26.
sqn_ms_derive() AK : 8b.c8.36.f1.f7.3d.
sqn_ms_derive() SQN_MS : fe.29.88.83.84.d8.
sqn_ms_derive() MAC_S : b1.42.4a.24.71.49.c0.26.

Any workaround ? Maybe setting both the UE and HSS SQN to 0 ? If so, how is it possible to set them ?

**Comment by Rodolphe-B** [comment]
The hack makes HSS use the proper data (AUTS).

The resynch part seems not to be called because the computed MAC_s does not correspond to the MAC_s sent by UE.

The computation needs :
opc: **c42449363bbad02b66d16bc975d77cc1** filled in HSS database when we run `oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey`
key: **fec86ba6eb707ed08905757b1bb44b8f** filled in HSS when we run `./data_provisioning_users --apn default --apn2 internet --key fec86ba6eb707ed08905757b1bb44b8f ...`
rand_p: **9649533250ac390e0099435f63e3a91d** sent by MME in the authentication request that triggered the synch failure at UE side
sqn_ms: **874b5627554a** calculated by HSS using AUTS sent by UE in the authentication failure notification, and using AK derived from key and rand
amf: **[0,0]**

rand_p and sqn_ms are example values that I captured with wireshark and with HSS logs.

If any of these sounds incorrect, either I missunderstood the code, either something isn't correct in the code.

**Comment by dchard** [comment]
@Rodolphe-B 

I responded to your mail.

"The resynch part seems not to be called"

Its good that we got to the same conclusion :-)
That SQN_MS looks huge. On test cards I am using quite extensibly, I was not able to see a higher SQN than the 10000 range.

**Comment by Rodolphe-B** [comment]
@dchard I believe that the SQN_MS is huge because it is calculated (by f5 function) from a 32 bytes random.

On the test cards, did you see the SQN_MS sent by the USIM in an Authentication Failure packet ?
As far as I experienced, the SQN_MS sent by the USIM after a Synch Failure seems random to me, because it is always calculated by the f5 function.

**Comment by Rodolphe-B** [comment]
Issue resolved for me. It seems that there is an issue with oai_hss script that cuts hex numbers.

Example : the OAI USIM has 
`OPc = e734f8734007d6c5ce7a0508809e7e9c`

And when I run 

It gives: 

```
$ oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey
Options::jsonConfig            : /usr/local/etc/oai/hss_rel14.json
Options::diameterconfiguration : /usr/local/etc/oai/freeDiameter/hss_rel14_fd.conf
Options::cassserver            : 127.0.0.1
Options::cassuser              : root
Options::casspwd               : root
Options::cassdb                : vhss
Options::randvector            : 1
Options::roamallow             : 1
Options::optkey                : 1006020f0a478bf6b699f15c062e42b3
Options::reloadkey             : 0
Options::onlyloadkey           : 1
Options::gtwport               : 9080
Options::gtwhost               : *
Options::resthost              : 9081
Options::synchimsi             : 
Options::synchauts             : 
Initialized random


******************************************
IMSI:208930000000001
KEY :8baf473f2f8fd09487cccbd7097c6862
OPC :e734f873407d6c5ce7a58809e7e9c
RijndaelKeySchedule: K 8BAF473F2F8FD09487CCCBD7097C6862
Compute opc:
	K:	8BAF473F2F8FD09487CCCBD7097C6862
	In:	1006020F0A478BF6B699F15C062E42B3
	Rinj:	F732FA7C4A405D3378E3F45486B03C2F
	Out:	E734F8734007D6C5CE7A0508809E7E9C
NEW OPC :e734f873407d6c5ce7a58809e7e9c
******************************************
UPDATE vhss.users_imsi SET OPc='e734f873407d6c5ce7a58809e7e9c' WHERE imsi='208930000000001';
```


First (USIM config):
e7 34 f8 73 40 **07** d6 c5 ce 7a **05** **08** 80 9e 7e 9c
Second (HSS):
e7 34 f8 73 40 **7** d6 c5 ce 7a **5** **8** 80 9e 7e 9c**

We can see that some zeros are cropped out.

I manually updated the HSS with the good OPc (first one), it now works well.

**Comment by wangchao10101** [comment]
@Rodolphe-B

**Comment by wangchao10101** [comment]
@Rodolphe-B

**Comment by wangchao10101** [comment]
I think the root cause of this issue is not oai_hss script that cuts hex numbers.

because I run oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey
the print is below：
Options::jsonConfig            : /usr/local/etc/oai/hss_rel14.json
Options::diameterconfiguration : /usr/local/etc/oai/freeDiameter/hss_rel14_fd.conf
Options::cassserver            : 127.0.0.1
Options::cassuser              : root
Options::casspwd               : root
Options::cassdb                : vhss
Options::randvector            : 1
Options::roamallow             : 1
Options::optkey                : FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
Options::reloadkey             : 0
Options::onlyloadkey           : 1
Options::gtwport               : 9080
Options::gtwhost               : *
Options::resthost              : 9081
Options::synchimsi             : 
Options::synchauts             : 
Initialized random


******************************************
IMSI:460700123456803
KEY :11111111111111111111111111111111
OPC :77d7f4d3292d6c926a85886abfe08bba
RijndaelKeySchedule: K 11111111111111111111111111111111
Compute opc:
        K:      11111111111111111111111111111111
        In:     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        Rinj:   88280B2CD6D2936D957A7795401F7445
        Out:    77D7F4D3292D6C926A85886ABFE08BBA
NEW OPC :77d7f4d3292d6c926a85886abfe08bba
******************************************
UPDATE vhss.users_imsi SET OPc='77d7f4d3292d6c926a85886abfe08bba' WHERE imsi='460700123456803';

and this OPc (77 d7 f4 d3 29 2d 6c 92 6a 85 88 6a bf e0 8b ba) is same with USIM config.

I think maybe @dchard is right : "....it seems even though the MME sends a resynchronization AVP, the HSS just tries to do a normal auth, and a resynch part of the code is not even called."

**Comment by wangchao10101** [comment]
@Rodolphe-B I try to modify like that：
/src/hss_rel14/src/s6as6d_impl.cpp
....
         if (auts_set) {
             sqn = sqn_ms_derive_cpp (imsisec.opc, imsisec.key, **auts + 16**, imsisec.rand);
             if (sqn != NULL) {
 
               //We succeeded to verify SQN_MS...

now UE can process Authentication and security successfully.   but when UE try to active default bearer ,  MME has no response ，because of  Processing timeout for timer_id 0x7f85a4001280 and arg 0x7f85a4004880。whether ESM flag =0 or ESM =1.

with ESM flag = 1, I check the APN  in DB，that is same with  UE send .

if you meet this issue, could you share your method? please.

**Comment by dreibh** [comment]
> Issue resolved for me. It seems that there is an issue with oai_hss script that cuts hex numbers.
> 
> Example : the OAI USIM has
> `OPc = e734f8734007d6c5ce7a0508809e7e9c`
> 
> And when I run `oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey`
> 
> It gives:
> 
> ```
> $ oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey
> Options::jsonConfig            : /usr/local/etc/oai/hss_rel14.json
> Options::diameterconfiguration : /usr/local/etc/oai/freeDiameter/hss_rel14_fd.conf
> Options::cassserver            : 127.0.0.1
> Options::cassuser              : root
> Options::casspwd               : root
> Options::cassdb                : vhss
> Options::randvector            : 1
> Options::roamallow             : 1
> Options::optkey                : 1006020f0a478bf6b699f15c062e42b3
> Options::reloadkey             : 0
> Options::onlyloadkey           : 1
> Options::gtwport               : 9080
> Options::gtwhost               : *
> Options::resthost              : 9081
> Options::synchimsi             : 
> Options::synchauts             : 
> Initialized random
> 
> 
> ******************************************
> IMSI:208930000000001
> KEY :8baf473f2f8fd09487cccbd7097c6862
> OPC :e734f873407d6c5ce7a58809e7e9c
> RijndaelKeySchedule: K 8BAF473F2F8FD09487CCCBD7097C6862
> Compute opc:
> 	K:	8BAF473F2F8FD09487CCCBD7097C6862
> 	In:	1006020F0A478BF6B699F15C062E42B3
> 	Rinj:	F732FA7C4A405D3378E3F45486B03C2F
> 	Out:	E734F8734007D6C5CE7A0508809E7E9C
> NEW OPC :e734f873407d6c5ce7a58809e7e9c
> ******************************************
> UPDATE vhss.users_imsi SET OPc='e734f873407d6c5ce7a58809e7e9c' WHERE imsi='208930000000001';
> ```
> 
> First (USIM config):
> e7 34 f8 73 40 **07** d6 c5 ce 7a **05** **08** 80 9e 7e 9c
> Second (HSS):
> e7 34 f8 73 40 **7** d6 c5 ce 7a **5** **8** 80 9e 7e 9c**
> 
> We can see that some zeros are cropped out.
> 
> I manually updated the HSS with the good OPc (first one), I have now an other error, but not related to this issue.



> First (USIM config):
> e7 34 f8 73 40 **07** d6 c5 ce 7a **05** **08** 80 9e 7e 9c
> Second (HSS):
> e7 34 f8 73 40 **7** d6 c5 ce 7a **5** **8** 80 9e 7e 9c**
> 
> We can see that some zeros are cropped out.

I can confirm the issue with the missing "0" characters. I fixed this problem in this pull request: https://github.com/OPENAIRINTERFACE/openair-cn/pull/71

**Comment by dchard** [comment]
It seems this issue is non-existent in the way I thought it is.

The short summary is this:

If the SQN of the USIM and the HSS DB gets out of sync, there is no procedure to get it re-snychronized. If the SQn gets out of sync, the UE responds with Auth failure EMM cause #21 "synch failure". In this case, the MME should delete all auth vectors for the IMSI and request new vectors from the HSS, then repeat the auth procedure. But if the HSS really contains incorrect SQN values, this will fail again, and again. So what the standard calls "re-snychronization", is kind of misleading.

In theory, if only the SQN is incorrect, the MME could derive the correct SQN from the AUTS response of the UE, but the MME cannot update the SQN value in the HSS, there is no procedure for that.

I am closing this issue, as it is not an issue.
